[theme]
primaryColor = "#D2F438"
backgroundColor = "#F3F6F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1D1A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
